#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
#
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := msg_decoder.cpp msg_logger.cpp pause_detector.cpp

# header files in this project
HEADERS := msg_decoder.hpp msg_listener.hpp msg_logger.hpp pause_detector.hpp pause_listener.hpp IR_receiver.hpp

# other places to look for files for this project
SEARCH  :=

# set REATIVE to the next higher directory
# and defer to the Makefile.due there
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.due
